//
//  File.swift
//  
//
//  Created by Eric Anderson on 12/17/20.
//

import Foundation

extension SFSymbolicator {
    
    public enum Component: String, CaseIterable {
        case h
        case bicycle
        case display
        case x
        case lasso
        case plus
        case watchface
        case pull
        case gen4
        case bullet
        case cross
        case tropicalstorm
        case dotmatrix
        case alignright
        case braille
        case externaldrive
        case roundedtop
        case captions
        case l2
        case paragraphsign
        case u
        case r2
        case wonsign
        case squarepath
        case and
        case doubledecker
        case number
        case l
        case j
        case superscript
        case applewatch
        case timemachine
        case shadow
        case bottomhalf
        case offgrid
        case gear
        case dpad
        case capslock
        case bolt
        case gauge
        case greetingcard
        case wand
        case middle
        case phone
        case projective
        case viewfinder
        case top
        case wave
        case left
        case below
        case esim
        case lt
        case righttriangle
        case gyroscope
        case power
        case goforward
        case w
        case rain
        case sdcard
        case bubble
        case house
        case cart
        case pass
        case leaf
        case xserve
        case eye
        case d
        case grid
        case walk
        case wallet
        case horizontal
        case path
        case tunnel
        case at
        case exclamationmark
        case slash
        case envelope
        case link
        case percent
        case hryvniasign
        case z
        case hands
        case capsulepath
        case flame
        case clock
        case tv
        case clipboard
        case nairasign
        case pointed
        case lessthan
        case badge
        case infinity
        case lefthalf
        case full
        case swap
        case nose
        case textformat
        case snow
        case max
        case creditcard
        case playpause
        case heart
        case delete
        case ellipse
        case sunrise
        case internaldrive
        case music
        case paintbrush
        case zigzag
        case apps
        case b
        case point
        case tap
        case person
        case staroflife
        case tag
        case bag
        case tray
        case rupeesign
        case l1
        case dashed
        case octagon
        case zr
        case indianrupeesign
        case trianglepath
        case wifi
        case rublesign
        case questionmark
        case airpod
        case tower
        case tram
        case rack
        case joystick
        case function
        case bitcoinsign
        case dot
        case bin
        case speaker
        case trianglebadge
        case connected
        case roundedbottom
        case die
        case q
        case increase
        case app
        case compact
        case airplane
        case smoke
        case lirasign
        case thermometer
        case a
        case shift
        case r1
        case mic
        case rb
        case sparkles
        case counterclockwise
        case speedometer
        case arrowshape
        case candybarphone
        case stop
        case hurricane
        case cruzeirosign
        case stethoscope
        case double
        case min
        case ladybug
        case location
        case equal
        case greaterthan
        case squareroot
        case shekelsign
        case keyboard
        case pin
        case n
        case aspectratio
        case aligncenter
        case australsign
        case video
        case fog
        case square
        case map
        case airpodspro
        case play
        case cloud
        case chevron
        case extreme
        case faxmachine
        case list
        case lock
        case pause
        case escape
        case iphone
        case arrowtriangle
        case centsign
        case thumbsup
        case airpodpro
        case radio
        case film
        case smiling
        case scissors
        case globe
        case star
        case control
        case quotelevel
        case indent
        case bandage
        case y
        case scroll
        case lb
        case car
        case moon
        case justifyright
        case m
        case down
        case paintpalette
        case sleet
        case c
        case capsule
        case shield
        case halffull
        case v
        case server
        case triangle
        case paperplane
        case wrench
        case metronome
        case level
        case filters
        case macpro
        case stack
        case e
        case gen1
        case eyebrow
        case decrease
        case gift
        case headphones
        case tuningfork
        case florinsign
        case stopwatch
        case circle
        case sum
        case megaphone
        case guaranisign
        case underline
        case hammer
        case abc
        case screwdriver
        case hexagon
        case answer
        case cedisign
        case righthalf
        case zzz
        case printer
        case branch
        case book
        case pills
        case message
        case pc
        case pianokeys
        case bottom
        case rhombus
        case folder
        case ticket
        case cursor
        case eyes
        case thumbsdown
        case lungs
        case airport
        case sterlingsign
        case eyedropper
        case highlighter
        case p
        case hail
        case hourglass
        case pesosign
        case scalemass
        case puzzlepiece
        case briefcase
        case gen3
        case binoculars
        case heavyrain
        case figure
        case latch
        case flipphone
        case rotation
        case forward
        case k
        case teletype
        case bounce
        case rays
        case camera
        case snowflake
        case sun
        case right
        case rotate
        case perspective
        case scribble
        case waveform
        case drop
        case calendar
        case tengesign
        case antenna
        case dial
        case north
        case redaction
        case coloncurrencysign
        case s
        case r
        case paperclip
        case yensign
        case tip
        case gen2
        case haze
        case closed
        case tugriksign
        case out
        case selection
        case mustache
        case timeline
        case off
        case slider
        case landscape
        case ipod
        case onehanded
        case shippingbox
        case i
        case alignleft
        case connection
        case o
        case opticaldiscdrive
        case size
        case loupe
        case turkishlirasign
        case multiply
        case hand
        case plusminus
        case minus
        case laptopcomputer
        case frame
        case express
        case crop
        case ellipsis
        case fill
        case crown
        case dollarsign
        case larisign
        case italic
        case sunset
        case homepod
        case quote
        case timer
        case banknote
        case bookmark
        case option
        case key
        case giftcard
        case flag
        case to
        case turn
        case seal
        case checkmark
        case light
        case rectangle
        case zl
        case drizzle
        case stars
        case ruler
        case circlepath
        case alarm
        case outline
        case clear
        case kipsign
        case lifepreserver
        case t
        case millsign
        case text
        case dottedunderline
        case rosette
        case on
        case pencil
        case arrow
        case ipodshuffle
        case network
        case note
        case portrait
        case command
        case hare
        case alt
        case bahtsign
        case mappin
        case variable
        case trash
        case gobackward
        case personalhotspot
        case record
        case books
        case newspaper
        case eyeglasses
        case eurosign
        case gearshape
        case textbox
        case barometer
        case ipad
        case archivebox
        case open
        case ipodtouch
        case rt
        case ant
        case justifyleft
        case earpods
        case divide
        case signature
        case scanner
        case vertical
        case simcard
        case eject
        case bus
        case tophalf
        case merge
        case shuffle
        case diamond
        case doc
        case strikethrough
        case icloud
        case hifispeaker
        case backward
        case magnifyingglass
        case bell
        case studentdesk
        case inverse
        case gamecontroller
        case f
        case ear
        case paper
        case bonjour
        case uturn
        case g
        case tortoise
        case manatsign
        case umbrella
        case lightbulb
        case xmark
        case francsign
        case dust
        case mouth
        case clockwise
        case wind
        case bed
        case dongsign
        case pesetasign
        case line
        case macmini
        case tornado
        case hearingaid
        case scale
        case end
        case clap
        case appletv
        case opticaldisc
        case move
        case homebutton
        case comb
        case dash
        case deskclock
        case oval
        case radiowaves
        case draw
        case desktopcomputer
        case bold
        case skew
        case airpods
        case ecg
        case face
        case raised
        case flashlight
        case guitars
        case justify
        case up
    }
}
